name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
      fail-fast: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    
    - name: Clear npm cache
      run: npm cache clean --force
    
    - name: Install dependencies
      run: npm install --no-optional
    
    - name: Run unit tests
      run: npm run test:unit
    
    - name: Run integration tests (allowed to fail)
      run: npm run test:integration || echo "Integration tests failed - this is expected due to API limitations"
      continue-on-error: true
      
  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
        check-latest: true
    
    - name: Clear npm cache
      run: npm cache clean --force
    
    - name: Install dependencies
      run: npm install --no-optional
    
    - name: Validate package
      run: npm run validate
    
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
